### ISSUE TITLE
Failed to add cover art

### ISSUE THREAD

**Issue by RaedAlbarakati** [LaurenceRawlings/savify#12] opened 2020-12-09 08:57 UTC
* Savify version: v2.0.10
* Python version: 3.8.2
* Operating System: Win10 64x

### Description

I followed the installation steps and everything works fine, but I have the following issue:

[DEBUG] [download] Downloading playlist: James TW - When You Love Someone (AUDIO)
[DEBUG] [youtube:search] query "James TW - When You Love Someone (AUDIO)": Downloading page 1
[DEBUG] [youtube:search] playlist James TW - When You Love Someone (AUDIO): Downloading 1 videos
[DEBUG] [download] Downloading video 1 of 1
[DEBUG] [youtube] Zwu585LtGto: Downloading webpage
[ERROR] ERROR: Zwu585LtGto: YouTube said: Unable to extract video data
[DEBUG] [download] Finished downloading playlist: James TW - When You Love Someone (AUDIO)

Download Finished!
Completed 0/1 tracks in 2.4410s

Failed Tracks:

Track: When You Love Someone
Reason: Failed to add cover art.

*************

As you can see "Reason: Failed to add cover art." how to solve the add cover art issue?

Thanks.
![issue](https://user-images.githubusercontent.com/9073493/101607449-add3df80-3a15-11eb-8a15-5dd0b88a03e5.jpg)

**Comment by FGameCZ** [comment] 2020-12-18 19:27
Hi,
I have the same problem and I think it is caused by YouTube.

**Comment by FGameCZ** [comment] 2020-12-18 19:54
#13

**Comment by FGameCZ** [comment] 2020-12-19 10:51
Python version works well. Hope it "solved" your issue too @RaedAlbarakati. More info here: https://stackoverflow.com/questions/63816790/youtube-dl-error-youtube-said-unable-to-extract-video-data

I think @LaurenceRawlings will solve this issue soon in .exe version.

**Comment by LaurenceRawlings** [comment] 2021-01-25 00:05
This seemed to be an issue with copying files when FFmpeg fails. I have now fixed this and also added an option to skip the cover art process. See the README for how to do this.

**Closed by LaurenceRawlings** 2021-01-25 00:05 UTC
Labels: bug
